CREATE DATABASE checkout;

USE checkout;

CREATE TABLE user (
  cookie VARCHAR(50) NOT NULL PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL,
  pw VARCHAR(18) NOT NULL,
  addressID INT NOT NULL,
  cardNumber INT NOT NULL,
  FOREIGN KEY(cardID) REFERENCES card(num),
  FOREIGN KEY(addressID) REFERENCES location(id)
)

CREATE TABLE card (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  num INT NOT NULL,
  CVV INT NOT NULL,
  expiration INT NOT NULL,
)

CREATE TABLE location (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  line1 VARCHAR(50) NOT NULL,
  line2 VARCHAR(50) DEFAULT '',
  city TEXT NOT NULL,
  currentState TEXT NOT NULL,
  zipcode INT NOT NULL,
)

